services:
  - type: web
    name: kame-game-hub-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/client
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
